### PR TITLE
Change Put Items section title

### PR DESCRIPTION
**Pull request by leits**

### CODE REVIEW

**Comment by leits** [comment]
Also maybe it makes sense to reorganize the endpoints list?
Start with the item creation, then basic operations, and then batch operations.
Like
1. Insert Item
2. Get Item
3. Update Item
4. Delete Item
5. Put Items
6. Query Items

WDYT?

**Comment by abdelhai** [comment]
@leits Put should be at position 1 as it is the recommended way to save an item (~2x faster than insert)
**put > insert > get > update > delete > query**

**Comment by leits** [comment]
I think it would be great if you mention it in your docs!

Also, put faster because it doesn't check if there is an object before writing, am I right?

**Comment by abdelhai** [comment]
We have it in the [SDK](https://docs.deta.sh/docs/base/sdk#insert) but should add it to the HTTP docs too.

Yes, insert ~= get + put.

**Pull request merged**
